### ISSUE TITLE
Le falta un ";"

### ISSUE THREAD

**Issue by DiiegoAG** [Antonio072/TallerCIITEC2018#16]
![captura de pantalla 2018-11-14 a la s 12 32 36](https://user-images.githubusercontent.com/45045082/48504043-6b754f80-e809-11e8-8450-cfda34e7fb46.png)

**Comment by Antonio072** [comment]
Ah mira, te falta un punto y coma despues de declarar tu arreglo.

**Comment by DiiegoAG** [comment]
Gracias 😃 se arreglo el programa 👍
